import mysql.connector

# website_analyzed is the name for the website 
website_analyzed = ""
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="PZZwsmapE4-Uk:6"
)
mycursor = mydb.cursor()
sqlFormula = ""


# Initiates the database and adds the data into it. If there is already a database, it adds the elements to the existing database
# scrapedFromWebsite is a list containing tuples generated by the scraper Ex: list((string, string))
# website is a string containing an identifier for the website Ex: wsj.com
def initiate_database(scrapedFromWebsite, website):
    #Check that the proper database exists
    mycursor.execute("SHOW DATABASES LIKE 'headlinedb'")
    #if database does not exist, create one
    if (len(mycursor.fetchall()) == 0):
        mycursor.execute("CREATE DATABASE headlinedb")

    mycursor.execute("USE headlinedb") #@MARKER

    website_analyzed = website

    mycursor.execute("SHOW TABLES LIKE '" + website_analyzed + "'")
    if (len(mycursor.fetchall()) == 0):
        mycursor.execute("CREATE TABLE " + website_analyzed + " (date VARCHAR(255), headline VARCHAR(255))")

    sqlFormula = "INSERT INTO " + website_analyzed + "(date, headline) VALUES (%s, %s)"

    #uses the sqlFormula to put the data in the database
    mycursor.executemany(sqlFormula, scrapedFromWebsite)
    mydb.commit()

# Prints all the data to the standard output location (terminal)
def printAllData():
    mycursor.execute("SELECT * FROM wsjcom")

    for row in mycursor.fetchall():
        print(row)

# add the element to the database
def addToDatabase(listOfTuple):
    mycursor.executemany(sqlFormula, listOfTuple)
    mydb.commit()

# delete the entries in the database with the given string date
# yearMonthDay is a string containing the date to delete Ex: "2000/01/01"
def deleteAllAtDate(yearMonthDay):
    mycursor.execute("DELETE FROM " + website_analyzed + " WHERE date = '" + yearMonthDay + "'")
    mydb.commit()

# delete the entries in the database with the given snippet
# snippet is a string. Any headline that contains this string will be deleted Ex: "the" <- will delete any entry containing 'the'
def deleteHeadlineContaining(snippet):
    mycursor.execute("DELETE FROM " + website_analyzed + " WHERE headline = '%" + snippet + "%'")
    mydb.commit()

# delete the database and all of its information
def clearDatabase():
    mycursor.execute("DROP DATABASE headlinedb")



# Example list generated by web scraper
exampleScrape = [("2019/08/17", "Fireman dies in wilfire"),
                      ("2015/12/12", "Bird eats a worm that turned out to be a tapeworm"),
                      ("2013/01/30", "Man loses fertility after a 5 day erection"),
                      ("2010/05/26", "Time news begins to make magazines"),
                      ("2005/09/01", "TOTAL DRAMA ACTION! New TV show appears")]

# ADD COMMANDS HERE (be careful if u dont use initiate database u need to set the cursor to the database using @MARKER)
#initiate_database(exampleScrape, "wsjcom")
#mycursor.execute("USE headlinedb")
#clearDatabase()